"""Shared validation issue code constants and outcome classification."""

DUPLICATE_INVOICE_NUMBER = "DUPLICATE_INVOICE_NUMBER"
POTENTIAL_DUPLICATE_INVOICE = "POTENTIAL_DUPLICATE_INVOICE"

PO_RECOVERED = "PO_RECOVERED"
PO_AMBIGUOUS = "PO_AMBIGUOUS"
PO_UNRESOLVED = "PO_UNRESOLVED"
PO_RESOLUTION_BLOCKED = "PO_RESOLUTION_BLOCKED"
PO_VENDOR_CONFLICT = "PO_VENDOR_CONFLICT"
PO_MISSING = "PO_MISSING"
PO_CLOSED = "PO_CLOSED"
INVALID_PO_REFERENCE = "INVALID_PO_REFERENCE"

AMBIGUOUS_LINE_MATCH = "AMBIGUOUS_LINE_MATCH"
UNMATCHED_LINE_ITEM = "UNMATCHED_LINE_ITEM"
MISSING_PO_COVERAGE = "MISSING_PO_COVERAGE"
LINE_ITEM_VENDOR_CONFLICT = "LINE_ITEM_VENDOR_CONFLICT"

AMBIGUOUS_VENDOR = "AMBIGUOUS_VENDOR"
DUPLICATE_VENDOR_GSTIN = "DUPLICATE_VENDOR_GSTIN"
VENDOR_NOT_FOUND = "VENDOR_NOT_FOUND"

DUPLICATE_ISSUE_CODES = frozenset(
    {
        DUPLICATE_INVOICE_NUMBER,
        POTENTIAL_DUPLICATE_INVOICE,
    },
)

AMBIGUOUS_ISSUE_CODES = frozenset(
    {
        PO_AMBIGUOUS,
        AMBIGUOUS_LINE_MATCH,
        AMBIGUOUS_VENDOR,
    },
)

STRUCTURAL_UNRESOLVED_ISSUE_CODES = frozenset(
    {
        PO_UNRESOLVED,
        PO_RESOLUTION_BLOCKED,
        MISSING_PO_COVERAGE,
        PO_VENDOR_CONFLICT,
        LINE_ITEM_VENDOR_CONFLICT,
        VENDOR_NOT_FOUND,
        PO_MISSING,
        PO_CLOSED,
        DUPLICATE_VENDOR_GSTIN,
    },
)

RECOVERY_CONFIRMATION_OPEN_CODES = frozenset(
    {
        PO_RECOVERED,
    },
)

RECOVERABLE_ISSUE_CODES = frozenset(
    {
        "MISSING_INVOICE_NUMBER",
        VENDOR_NOT_FOUND,
        PO_MISSING,
        PO_RECOVERED,
        INVALID_PO_REFERENCE,
    },
)

HARD_STOP_ISSUE_CODES = frozenset(
    {
        AMBIGUOUS_VENDOR,
        DUPLICATE_VENDOR_GSTIN,
        PO_UNRESOLVED,
        PO_RESOLUTION_BLOCKED,
        LINE_ITEM_VENDOR_CONFLICT,
        PO_VENDOR_CONFLICT,
    },
)

REROUTE_ISSUE_CODES = frozenset()
