VALIDATION_EVENT_VERSION = 1
VALIDATION_EVENT_TYPE_COMPLETED = "validation.completed"
VALIDATION_EVENT_TYPE_PENDING_REVIEW = "validation.pending_review"
VALIDATION_EVENT_TYPE_REJECTED = "validation.rejected"

VALIDATION_EVENT_TYPES = frozenset(
    {
        VALIDATION_EVENT_TYPE_COMPLETED,
        VALIDATION_EVENT_TYPE_PENDING_REVIEW,
        VALIDATION_EVENT_TYPE_REJECTED,
    },
)
