VALIDATION_EVENT_VERSION = 1
VALIDATION_EVENT_TYPE_RESOLVED = "validation.resolved"
VALIDATION_EVENT_TYPE_RECOVERED = "validation.recovered"
VALIDATION_EVENT_TYPE_AMBIGUOUS = "validation.ambiguous"
VALIDATION_EVENT_TYPE_UNRESOLVED = "validation.unresolved"
VALIDATION_EVENT_TYPE_DUPLICATE = "validation.duplicate"

VALIDATION_EVENT_TYPES = frozenset(
    {
        VALIDATION_EVENT_TYPE_RESOLVED,
        VALIDATION_EVENT_TYPE_RECOVERED,
        VALIDATION_EVENT_TYPE_AMBIGUOUS,
        VALIDATION_EVENT_TYPE_UNRESOLVED,
        VALIDATION_EVENT_TYPE_DUPLICATE,
    },
)
